postgres: &postgres
  adapter: postgresql
  host: localhost
  min_messages: WARNING

development:
  <<: *postgres
  database: focus_dev

test:
  <<: *postgres
  database: focus_test

production:
  <<: *postgres
  database: focus
