postgres: &postgres
  adapter: postgresql
  host: localhost
  min_messages: WARNING

development:
  <<: *postgres
  database: jaredatron_dev

test:
  <<: *postgres
  database: jaredatron_test

production:
  <<: *postgres
  database: jaredatron
