#!/usr/bin/env node

/* eslint no-console: 0 */
'use strict';

const pgtools = require('pgtools');
const { database, ...config } = require('../database').config;

pgtools.dropdb(config, database, function (error) {
  if (error) {
    if (error.message.includes(`database "${database}" does not exist`)){
      console.log(`database "${database}" does not exist`);
      process.exit(0);
    }
    console.error(error.message);
    process.exit(1);
  }
  console.log(`dropped database "${database}"`);
  process.exit(0);
});
