export { login } from './login'
export {   loadWikiIndex } from './loadWikiIndex'
export { filterWikiIndex } from './filterWikiIndex'
export {   loadWikiPage  } from './loadWikiPage'
export { publishLocation, setLocation, replaceLocation } from 'lib/location'
